# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""



"""# Computação Gráfica e Processamento de Imagens
### FCT-ITEC-UFPA
### Nome: Erick Mamede Silva da Costa
### Matrícula: 201906840033

## Tarefa 01
"""

!git clone https://github.com/erickmamede/PDI.git

# Carrega módulos do Python
import numpy as np                # funções matemáticas 
import matplotlib.pyplot as plt   # traçado de gráficos
import cv2 as cv2                  # biblioteca opencv (visão computacional)
from google.colab.patches import cv2_imshow # patch para OpenCV
import scipy                      # funções diversas (processamento de sinais e imagem)


path = '/content/PDI/tarefa01.jpg' # caminho
nome_da_imagem = 'tarefa01.jpg' # nome da imagem


im_colour = cv2.imread( path ) # Lê uma imagem usando opencv

cv2_imshow(im_colour)